spring.application.name=registry-service
server.port=8761

# Set hostname if needed (for Docker networking)
eureka.instance.hostname=registry-service

# This is a registry, not a client
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false
